account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.loginView, name='login_view'),
    path('create/', views.user_create_view, name='user_create'),
    path('user_list/', views.user_list, name='user_list'),
    path('update/<int:user_id>/', views.user_update, name='user_update'),
    path('delete/<int:user_id>/', views.user_delete, name='user_delete'),
    path('logout/', views.logout_view, name='logout_view'),
    path('group/list/', views.group_list, name='group_list'),
    path('group/create/', views.group_create, name='group_create'),
    path('group/update/<int:group_id>/', views.group_update, name='group_update'),
    path('group/delete/<int:group_id>/', views.group_delete, name='group_delete'),
    path('watchlist/add/<int:company_id>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('watchlist/remove/<int:company_id>/', views.remove_from_watchlist, name='remove_from_watchlist'),
    path('handle-agm-notification/<int:agm_id>/', views.handle_agm_notification_action, name='handle_agm_notification_action')
]

company/urls.py
from django.urls import path
from . import views

app_name = 'company'

urlpatterns = [
    path('', views.company_list, name='company_list'),
    path('create/', views.company_create, name='company_create'),
    path('update/<int:company_id>/', views.company_update, name='company_update'),
    path('delete/<int:company_id>/', views.company_delete, name='company_delete'),
    path('company_url_update/<int:company_url_id>/', views.update_company_url, name='update_company_url'),
    path('bod/create/', views.board_of_director_create, name='board_of_director_create'),
    path('bod/update/<int:bod_id>/', views.board_of_director_update, name='board_of_director_update'),
    path('bod/delete/<int:bod_id>/', views.board_of_director_delete, name='board_of_director_delete'),
    path('category/list', views.category_list, name='category_list'),
    path('category/create', views.category_create, name='category_create'),
    path('category/update/<int:category_id>/', views.category_update, name='category_update'),
    path('category/delete/<int:category_id>/', views.category_delete, name='category_delete'),
    path('floorsheet/list', views.floorsheet_list, name='floorsheet_list'),
    path('floorsheet/create', views.floorsheet_create, name='floorsheet_create'),
    path('floorsheet/update/<int:floorsheet_id>/', views.floorsheet_update, name='floorsheet_update'),
    path('floorsheet/delete/<int:floorsheet_id>/', views.floorsheet_delete, name='floorsheet_delete'),
    path('market/today/', views.today_market, name='today_market'),
    path('import/company/', views.import_company_data, name='import_company_data'),
    path('chart/data/<int:company_id>/', views.company_data_chart, name='company_data_chart'),
    path('data/create', views.company_data_create, name='company_data_create'),
    path('agm/list/', views.agm_list, name='agm_list'),
    path('agm/create/', views.agm_create, name='agm_create'),
    path('agm/update/<slug:agm_slug>/', views.agm_update, name='agm_update'),
    path('agm/delete/<slug:agm_slug>/', views.agm_delete, name='agm_delete'),
]

scrapper/urls.py
from django.urls import path
from . import views

app_name = 'scrapper'

urlpatterns = [
    path('detail/', views.company_detail, name='company_detail'),
    path('detail/admin/<int:company_id>/', views.company_detail_admin, name='company_detail_admin'),
    path('nepse/<int:company_id>/', views.scrap_from_nepse, name='scrap_from_nepse'),
    path('merolagani/<int:company_id>/', views.scrap_from_mero_lagani, name='scrap_from_mero_lagani'),
    path('sharesansar/<int:company_id>/', views.scrap_from_share_sansar, name='scrap_from_share_sansar'),
]

scrapping_2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import dashboard

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('company/', include('company.urls', namespace='company')),
    path('scrapper/', include('scrapper.urls', namespace='scrapper')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scrapper/models.py
from django.db import models

scrapper/views.py
import requests

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.utils import timezone

from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.common.exceptions import InvalidArgumentException
from selenium.webdriver.support import expected_conditions as EC

from company.models import CompanyData, Company
from scrapper.admin import CompanyDataResource
from .utils import list_to_dict

# Create your views here.

def filter_company_data_by_date(company, start_date, end_date):
    company_data = CompanyData.objects.filter(company=company, created_at__date__range=[start_date, end_date])
    return company_data

def company_detail_admin(request, company_id):
    today = timezone.now().date()
    context = {
        'today': today.strftime('%Y-%m-%d'),
    }
    try:
        company = Company.objects.get(id=company_id)
        today_company_data = CompanyData.objects.get(company=company, created_at__date=today)
    except Company.DoesNotExist:
        company = None
        messages.success(request, "Company does not exists")
    except CompanyData.DoesNotExist:
        today_company_data = None
        messages.error(request, "No data found")
    finally:
        context['company'] = company
        context['company_data'] = today_company_data

    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')

    if start_date:
        filtered_company_data = filter_company_data_by_date(company, start_date, end_date)
        context['floorsheet'] = filtered_company_data.order_by('-updated_at')
        context['start_date'] = start_date
        context['end_date'] = end_date
    else:
        context['floorsheet'] = company.company_data.all().order_by('-updated_at')

    return render(request, 'scrapper/detail.html', context=context)

def company_detail(request):
    company = request.user.company
    today = timezone.now().date()
    context = {
        'company': company,
    }

    if company is None:
        messages.error(request, "User is not assoiciated with any company")
    else:
        try:
            company_data = CompanyData.objects.get(company=company, created_at__date=today)
        except CompanyData.DoesNotExist:
            company_data = None
            messages.error(request, "No data found")
        finally:
            context['company_data'] = company_data
    
    context['floorsheet'] = company.company_data.all().order_by('-updated_at')
    return render(request, 'scrapper/detail.html', context=context)


def scrap_from_nepse(request, company_id):
    if request.method == 'POST':
        today = timezone.now()
        company = Company.objects.get(id=company_id)

        try:
            company_data = CompanyData.objects.get(company=company, created_at__date=today.date())
        except CompanyData.DoesNotExist:
            company_data = CompanyData(company=company, created_at=today, updated_at=today)

        nepse_url = company.urls.nepse_url     # the urls should be initialized from the company update page

        driver = webdriver.Chrome()
        try:
            driver.get(nepse_url)
        except InvalidArgumentException:
            messages.error("Error: Invalid Nepse url!")
        else:
            table = WebDriverWait(driver, 10).until(
                EC.visibility_of_element_located((By.CLASS_NAME, 'table'))
            )

            table_soup = BeautifulSoup(table.get_attribute('outerHTML'), 'html.parser')

            data_dict = {}

            tbody = table_soup.find('tbody')
            rows = tbody.find_all('tr')[1:-1]

            for row in rows:
                th_text = row.find('th').get_text(strip=True)
                td_text = row.find('td').get_text(strip=True)
                data_dict[th_text] = td_text

            company_data.last_scrapped_from = 'Nepse'
            company_data.last_traded_price = data_dict['Last Traded Price'][0:6]
            company_data.total_traded_quantity = data_dict['Total Traded Quantity']
            company_data.total_trades = data_dict['Total Trades']
            company_data.previous_day_close_price = data_dict['Previous Day Close Price']
            company_data.high_price_low_price = data_dict['High Price / Low Price']
            company_data.week_high_week_low = data_dict['52 Week High / 52 Week Low']
            company_data.open_price = data_dict['Open Price']
            company_data.close_price = data_dict['Close Price*']
            company_data.total_listed_shares = data_dict['Total Listed Shares']
            company_data.total_paid_up_value = data_dict['Total Paid up Value']
            company_data.market_capitalization = data_dict['Market Capitalization']
            company_data.save()
            messages.success(request, "Success: Data updated")
    redirect_url = request.META.get('HTTP_REFERER')
    return redirect(redirect_url)


def scrap_from_mero_lagani(request, company_id):
    if request.method == 'POST':
        today = timezone.now()
        company = Company.objects.get(id=company_id)

        try:
            company_data = CompanyData.objects.get(company=company, created_at__date=today.date())
        except CompanyData.DoesNotExist:
            print("Company data is not of today")
            company_data = CompanyData(company=company, created_at=today, updated_at=today)
        else:
            print("Company data is of today")
        
        mero_lagani_url = company.urls.mero_lagani_url
        response = requests.get(mero_lagani_url)
        soup = BeautifulSoup(response.text, 'html.parser')
        rows = soup.find_all('tr')

        table_data = {}
        for row in rows:
            try:
                th = row.find('th').get_text(strip=True)
                td = row.find('td').get_text(strip=True)
                table_data[th] = td  
            except AttributeError:
                table_data[th] = ""
        
        company_data.last_scrapped_from = 'Mero Lagani'
        company_data.total_listed_shares = table_data['Shares Outstanding']
        company_data.last_traded_price =table_data['Market Price']
        company_data.week_high_week_low = table_data['52 Weeks High - Low']
        company_data.market_capitalization = table_data['Market Capitalization']
        company_data.total_listed_shares = table_data['Listed Shares']
        company_data.total_paid_up_value = table_data['Total Paidup Value']
        company_data.save()
        messages.success(request, "Success: Data updated")
    redirect_url = request.META.get('HTTP_REFERER')
    return redirect(redirect_url)
    
def scrap_from_share_sansar(request, company_id):
    if request.method == 'POST':
        today = timezone.now()
        company = Company.objects.get(id=company_id)

        try:
            company_data = CompanyData.objects.get(company=company, created_at__date=today.date())
        except CompanyData.DoesNotExist:
            print("Company data is not of today")
            company_data = CompanyData(company=company, created_at=today, updated_at=today)
        else:
            print("Company data is of today")

        share_sansar_url = company.urls.share_sansar_url
        response = requests.get(share_sansar_url)
        soup = BeautifulSoup(response.text, 'html.parser')

        last_traded_price = soup.find('span', class_="comp-price").get_text(strip=True)
        second_rows = soup.find_all('div', class_=["second-row margin-bottom-15"])

        scrapped_data = {}
        for row in second_rows:
            arr = row.text.replace(' ', '').split('\n')
            arr_dict = list_to_dict(arr)
            scrapped_data.update(arr_dict)

        table = soup.find('table', id='myTableCInfo')
        rows = table.find_all('tr')
        
        for row in rows:
            cells = row.find_all('td')
            key = cells[0].get_text(strip=True).replace("\n", "")
            value = cells[1].get_text(strip=True).replace("\n", "")
            scrapped_data[key] = value

        company_data.last_scrapped_from = 'Share sansar'
        company_data.high_price_low_price= f"{scrapped_data['High']}/{scrapped_data['Low']}"
        company_data.week_high_week_low = scrapped_data['52WeekHigh-Low']
        company_data.total_listed_shares= scrapped_data['Listed Shares']
        company_data.total_paid_up_value= scrapped_data['Total Paid Up Value']
        company_data.last_traded_price = last_traded_price
        company_data.open_price= scrapped_data['Open']
        company_data.save()
        messages.success(request, "Success: Data updated")
    redirect_url = request.META.get('HTTP_REFERER')
    return redirect(redirect_url)
    
def export_company_data(request, company_data_id):
    if request.method == 'POST':
        qs = CompanyData.objects.get(id=company_data_id)
        dataset = CompanyDataResource().export(qs)
        format = 'xls'
        ds = dataset.xls
        response = HttpResponse(ds, content_type=f'{format}')
        response['Content-Disposition'] = f'attachment; filename={qs.company.name}.{format}'
        return response
    

scrapper/templates/scrapper/detail.html
{% extends 'base.html' %}
{% load group_tags %}

{% block title %}
{% if company %}
{{ company.name }}
{% else %}
company | detail
{% endif %}
{% endblock %}

{% block content %}

<div class="card text-left mb-4">
    <div class="card-body">
        {% include 'message.html' %}
        {% if company %}
        <div class="mb-4" style="display: flex; align-items: center; justify-content: space-between;">
            <h4 class="card-title mb-3">{{ company.name }}</h4>
            {% if request.user|user_in_groups:"super admin, super editor, company admin" %}
            <a href="{% url 'company:company_update' company.id %}" class="btn btn-outline-primary">Update</a>
            {% endif %}
        </div>
        <div class="mb-4" style="display: flex; align-items: center; gap: 16px">
            <form action="{% url 'scrapper:scrap_from_nepse' company.id %}" method="POST" style="display:inline">
                {% csrf_token %}
                <button class="btn btn-outline-primary">Nepse</button>
            </form>
            <form action="{% url 'scrapper:scrap_from_share_sansar' company.id %}" method="POST" style="display:inline">
                {% csrf_token %}
                <button class="btn btn-outline-primary">Share sansar</button>
            </form>
            <form action="{% url 'scrapper:scrap_from_mero_lagani' company.id %}" method="POST" style="display:inline">
                {% csrf_token %}
                <button class="btn btn-outline-primary">Mero lagani</button>
            </form>
        </div>
        {% endif %}
        {% if company_data is not None %}
        <div class="table-responsive">
            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row">Last Scrapped from: </th>
                        <td>{{ company_data.last_scrapped_from }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Created at: </th>
                        <td>{{ company_data.created_at|default:'-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Last updated: </th>
                        <td>{{ company_data.updated_at|default:'-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Last traded price: </th>
                        <td>{{ company_data.last_traded_price|default:'-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Total trades: </th>
                        <td>{{ company_data.total_traded_quantity|default:'-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Previous day close price: </th>
                        <td>{{ company_data.previous_day_close_price|default:'-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">High price/low price: </th>
                        <td>{{ company_data.high_price_low_price|default:'-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">52 weeks high/low: </th>
                        <td>{{ company_data.week_high_week_low|default:'-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Open price: </th>
                        <td>{{ company_data.open_price|default:'-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Close price: </th>
                        <td>{{ company_data.close_price|default:'-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Total listed shares: </th>
                        <td>{{ company_data.total_listed_shares|default:'-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Total paid up value: </th>
                        <td>{{ company_data.total_paid_up_value|default:'-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Market capitalization: </th>
                        <td>{{ company_data.market_capitalization|default:'-' }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
</div>

<div class="card mb-4">
    <div class="card-body">
        <h5 class="card-title">Floorsheet</h5>
        <form method="GET">
            <div style="display: flex; align-items: center; gap: 32px;">
                <div class="form-group">
                    <label for="start_date">From</label>
                    <input type="date" class="form-control" id="start_date" name="start_date" required max="{{ today }}" value="{{ start_date }}">
                </div>
                <div class="form-group">
                    <label for="end_date">Till</label>
                    <input type="date" class="form-control" id="end_date" name="end_date" value="{{ end_date }}" max="{{ today }}" required >
                </div>
               
                <button type="submit" class="btn btn-outline-primary">Filter</button>
            </div>
        </form>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Updated at</th>
                        <th scope="col">Source</th>
                        <th scope="col">LTP</th>
                        <th scope="col">Open price</th>
                        <th scope="col">Close price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in floorsheet %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td scope="row">{{ data.updated_at }}</td>
                        <td scope="row">{{ data.last_scrapped_from }}</td>
                        <td scope="row">{{ data.last_traded_price }}</td>
                        <td scope="row">{{ data.open_price }}</td>
                        <td scope="row">{{ data.close_price }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="card mb-4">
    <div class="card-body" style="display: flex; align-items: center; justify-content: space-between;">
        <div class="card-title mb-3">Graph</div>
    </div>
    <div class="card-body">
        <canvas id="totalTradedPriceChart" width="400" height="120"></canvas>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
document.addEventListener('DOMContentLoaded', function () {
    fetch('/company/chart/data/{{ company.id }}/')
        .then(response => response.json())
        .then(data => {
            var ctx = document.getElementById('totalTradedPriceChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: data.labels,
                    datasets: [{
                        label: 'Last Traded Price',
                        data: data.last_traded_price,
                        borderColor: '{{ company.primary_color }}',
                        borderWidth: 2,
                        fill: false,
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true,
                            title: {
                                display: true,
                                text: 'Last traded price'
                            }
                        },
                        responsive: true,
                        maintainAspectRatio: true,
                    }
                }
            });
        });
    });
</script>
{% endblock %}