account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.loginView, name='login_view'),
    path('create/', views.user_create_view, name='user_create'),
    path('user_list/', views.user_list, name='user_list'),
    path('update/<int:user_id>/', views.user_update, name='user_update'),
    path('delete/<int:user_id>/', views.user_delete, name='user_delete'),
    path('logout/', views.logout_view, name='logout_view'),
    path('group/list/', views.group_list, name='group_list'),
    path('group/create/', views.group_create, name='group_create'),
    path('group/update/<int:group_id>/', views.group_update, name='group_update'),
    path('group/delete/<int:group_id>/', views.group_delete, name='group_delete'),
    path('watchlist/add/<int:company_id>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('watchlist/remove/<int:company_id>/', views.remove_from_watchlist, name='remove_from_watchlist'),
    path('handle-agm-notification/<int:agm_id>/', views.handle_agm_notification_action, name='handle_agm_notification_action')
]

company/urls.py
from django.urls import path
from . import views

app_name = 'company'

urlpatterns = [
    path('', views.company_list, name='company_list'),
    path('create/', views.company_create, name='company_create'),
    path('update/<int:company_id>/', views.company_update, name='company_update'),
    path('delete/<int:company_id>/', views.company_delete, name='company_delete'),
    path('company_url_update/<int:company_url_id>/', views.update_company_url, name='update_company_url'),
    path('bod/create/', views.board_of_director_create, name='board_of_director_create'),
    path('bod/update/<int:bod_id>/', views.board_of_director_update, name='board_of_director_update'),
    path('bod/delete/<int:bod_id>/', views.board_of_director_delete, name='board_of_director_delete'),
    path('category/list', views.category_list, name='category_list'),
    path('category/create', views.category_create, name='category_create'),
    path('category/update/<int:category_id>/', views.category_update, name='category_update'),
    path('category/delete/<int:category_id>/', views.category_delete, name='category_delete'),
    path('floorsheet/list', views.floorsheet_list, name='floorsheet_list'),
    path('floorsheet/create', views.floorsheet_create, name='floorsheet_create'),
    path('floorsheet/update/<int:floorsheet_id>/', views.floorsheet_update, name='floorsheet_update'),
    path('floorsheet/delete/<int:floorsheet_id>/', views.floorsheet_delete, name='floorsheet_delete'),
    path('market/today/', views.today_market, name='today_market'),
    path('import/company/', views.import_company_data, name='import_company_data'),
    path('chart/data/<int:company_id>/', views.company_data_chart, name='company_data_chart'),
    path('data/create', views.company_data_create, name='company_data_create'),
    path('agm/list/', views.agm_list, name='agm_list'),
    path('agm/create/', views.agm_create, name='agm_create'),
    path('agm/update/<slug:agm_slug>/', views.agm_update, name='agm_update'),
    path('agm/delete/<slug:agm_slug>/', views.agm_delete, name='agm_delete'),
]

scrapping_2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import dashboard

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('company/', include('company.urls', namespace='company')),
    path('scrapper/', include('scrapper.urls', namespace='scrapper')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/forms.py
from django import forms
from .models import AGM, BoardOfDirector, Category, Company, CompanyData, CompanyUrls, Floorsheet, News

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'
        widgets = {
            'primary_color': forms.TextInput(attrs={'type': 'color'}),
            'secondary_color': forms.TextInput(attrs={'type': 'color'}),
        }

    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class CompanyDataForm(forms.ModelForm):
    SOURCES = [
        ('', '---------'),
        ('Nepse', 'Nepse'),
        ('Share sansar', 'Share sansar'),
        ('Mero lagani', 'Mero lagani'),
    ]

    last_scrapped_from = forms.ChoiceField(choices=SOURCES)
    class Meta:
        model = CompanyData
        fields = '__all__'
        widgets = {
            'created_at': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'updated_at': forms.DateTimeInput(attrs={'type': 'datetime-local'}),        
        }

    def __init__(self, *args, **kwargs):
        super(CompanyDataForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CompanyUrlsForm(forms.ModelForm):
    class Meta:
        model = CompanyUrls
        fields = ('nepse_url', 'mero_lagani_url', 'share_sansar_url')

    def __init__(self, *args, **kwargs):
        super(CompanyUrlsForm, self).__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class BoardOfDirectorForm(forms.ModelForm):
    class Meta:
        model = BoardOfDirector
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(BoardOfDirectorForm, self).__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class CompanyCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CompanyCategoryForm, self).__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class FloorsheetForm(forms.ModelForm):
    class Meta:
        model = Floorsheet
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(FloorsheetForm, self).__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(NewsForm, self).__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class AGMForm(forms.ModelForm):
    class Meta:
        model = AGM
        fields = ['company', 'title', 'description', 'file', 'date']
        widgets = {
            'date': forms.DateTimeInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(AGMForm, self).__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

company/views.py
from datetime import timedelta
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import FloatField, ExpressionWrapper, Func
from django.db.models.functions import Substr
from django.utils import timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle

from account.decorators import user_in_groups
from scrapper.admin import CompanyDataResource, CompanyResource

from .forms import AGMForm, BoardOfDirectorForm, CompanyCategoryForm, CompanyDataForm, CompanyForm, CompanyUrlsForm, FloorsheetForm
from .models import AGM, BoardOfDirector, Category, Company, CompanyData, CompanyUrls, Floorsheet

# Create your views here.
@user_in_groups(['super admin', 'super editor'])
def company_list(request):
    company_list = Company.objects.all()
    context = {
        'company_list' : company_list
    }
    if request.method == 'POST':
        if 'xls' in request.POST:
            dataset = CompanyResource().export(company_list)
            ds = dataset.xls
            response = HttpResponse(ds, content_type='xls')
            response['Content-Disposition'] = f'attachment; filename=company_list.xls'
        elif 'pdf' in request.POST:
            response = HttpResponse(content_type='application/pdf')
            response['Content-Disposition'] = f'attachment; filename="company_list.pdf"'

            doc = SimpleDocTemplate(response, pagesize=letter)
            elements = []
            table_data = [['Name', 'email', 'phone', 'symbol', 'Category']]

            for item in company_list:
                table_data.append([item.name, item.email, item.phone, item.symbol, item.category.name])
            
            table = Table(table_data)
            elements.append(table)
            doc.build(elements)
        return response

    return render(request, 'company/company_list.html', context=context)

@user_in_groups(['super admin'])
def company_create(request):
    if request.method == 'POST':
        form = CompanyForm(request.POST, request.FILES)
        if form.is_valid():
            new_company = form.save()
            CompanyUrls.objects.create(company=new_company)
            return redirect('company:company_list')
    
    context = {
        'form': CompanyForm()
    }
    return render(request, 'company/company_create.html', context=context)

@user_in_groups(['super admin', 'super editor', 'company admin'])
def company_update(request, company_id):
    company = get_object_or_404(Company, id=company_id)
    try:
        company_url = company.urls
    except:
        company_url = None

    if request.method == 'POST':
        form = CompanyForm(request.POST, request.FILES, instance=company)
        if form.is_valid():
            form.save()
            return redirect('company:company_list')
    else:
        form = CompanyForm(instance=company)
        company_url_form = CompanyUrlsForm(instance=company_url)

    context = {
        'form': form, 
        'company_url_form': company_url_form,
        'company_url': company_url,
        'company': company,
        'floorsheet': company.company_data.all().order_by('-updated_at'),
    }
    return render(request, 'company/company_update.html', context=context)

def company_data_chart(request, company_id):
    company = Company.objects.get(id=company_id)
    company_data = CompanyData.objects.filter(company=company).order_by('created_at')

    data = {
        'labels': [str(data.created_at.date()) for data in company_data],
        'last_traded_price': [data.last_traded_price for data in company_data],
    }

    return JsonResponse(data)

@user_in_groups(['super admin'])
def company_delete(request, company_id):
    company = Company.objects.get(id=company_id)
    if request.method == 'POST':
        company.delete()
        messages.success(request, "Company Deleted")
        return redirect('company:company_list')
    
    context = {
        'company': company
    }
    return render(request, 'company/company_delete.html', context=context)

@user_in_groups(['super admin', 'super editor', 'company admin'])
def update_company_url(request, company_url_id):
    if request.method == 'POST':
        company_urls = CompanyUrls.objects.get(id=company_url_id) 
        form = CompanyUrlsForm(request.POST, instance=company_urls)
        if form.is_valid():
            form.save()
            messages.success(request, "URLS updated")
        else:
            messages.error(request, form.errors)
        referring_url = request.META.get('HTTP_REFERER', None)
        return redirect(referring_url)
    
@user_in_groups(['super admin', 'super editor', 'company admin'])
def board_of_director_create(request):
    if request.method == 'POST':
        form = BoardOfDirectorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Success! BOD Added")
    context = {
        'form': BoardOfDirectorForm()
    }
    return render(request, 'company/bod_create.html', context=context)


@user_in_groups(['super admin', 'super editor', 'company admin'])
def board_of_director_update(request, bod_id):
    bod = BoardOfDirector.objects.get(id=bod_id)

    if request.method == 'POST':

        form = BoardOfDirectorForm(request.POST, instance=bod)
        if form.is_valid():
            form.save()
            messages.success(request, "Success! BOD Updated")
    context = {
        'form': BoardOfDirectorForm(instance=bod)
    }
    return render(request, 'company/bod_update.html', context=context)


@user_in_groups(['super admin', 'super editor', 'company admin'])
def board_of_director_delete(request, bod_id):
    member = BoardOfDirector.objects.get(id=bod_id)

    if request.method == 'POST':
        member.delete()
        messages.info(request, 'Info: BOD member deleted')
        return redirect('company:company_list')

    context = {
        'member': member
    }
    return render(request, 'company/bod_delete.html', context=context)


@user_in_groups(['super admin', 'super editor'])
def category_list(request):
    context = {
        'categories': Category.objects.all()
    }
    
    return render(request, 'company/category_list.html', context=context)


@user_in_groups(['super admin'])
def category_create(request):
    if request.method == 'POST':
        form = CompanyCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Success: New category created")
            return redirect('company:category_list')

    context = {
        'form': CompanyCategoryForm()
    }
    return render(request, 'company/category_create.html', context=context)

@user_in_groups(['super admin', 'super editor'])
def category_update(request, category_id):
    category = Category.objects.get(id=category_id)
    form = CompanyCategoryForm(instance=category)
    if request.method == 'POST':
        form = CompanyCategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, "Success: New category created")
            return redirect('company:category_list')

    context = {
        'form': CompanyCategoryForm(instance=category)
    }
    return render(request, 'company/category_update.html', context=context)

@user_in_groups(['super admin'])
def category_delete(request, category_id):
    category = Category.objects.get(id=category_id)
    if request.method == 'POST':
        category.delete()
        messages.success(request, "Success: Category deleted")
        return redirect('company:category_list')
    return render(request, 'company/category_delete.html')


@user_in_groups(['super admin', 'super editor'])
def floorsheet_list(request):
    floorsheets = Floorsheet.objects.all()
    context = {
        'floorsheets': floorsheets
    }

    return render(request, 'company/floorsheet_list.html', context=context)

@user_in_groups(['super admin',])
def floorsheet_create(request):
    context = {
        'form' : FloorsheetForm()
    }
    if request.method == 'POST':
        form = FloorsheetForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Floorsheet created")
            return redirect('company:floorsheet_list')
        
    return render(request, 'company/floorsheet_create.html', context=context)


@user_in_groups(['super admin', 'super editor'])
def floorsheet_update(request, floorsheet_id):
    floorsheet = Floorsheet.objects.get(id=floorsheet_id)
    if request.method == 'POST':
        form = FloorsheetForm(request.POST, instance=floorsheet)
        if form.is_valid():
            form.save()
            messages.success(request, "Floorsheet updated")
            return redirect('company:floorsheet_list')

    context = {
        'form' : FloorsheetForm(instance=floorsheet)
    }
    return render(request, 'company/floorsheet_update.html', context=context)


@user_in_groups(['super admin'])
def floorsheet_delete(request, floorsheet_id):
    floorsheet = Floorsheet.objects.get(id=floorsheet_id)
    if request.method == 'POST':
        floorsheet.delete()
        messages.success(request, "Floorsheet deleted")
        return redirect('company:floorsheet_list')
    context = {
        'floorsheet': floorsheet
    }
    return render(request, 'company/floorsheet_delete.html', context=context)


class Substring(Func):
    function = 'SUBSTRING'

@user_in_groups(['super admin', 'super editor'])
def today_market(request):
    today = timezone.now().date()
    first_company_data = CompanyData.objects.order_by('created_at')[0]
    start_date = first_company_data.created_at.date()

    while today >= start_date:
        today_company_data = CompanyData.objects.filter(created_at__date=today)
        if today_company_data.exists():

company/templates/company/agm_list.html
{% extends 'base.html' %}
{% block title %} Company | List {%endblock %}
{% block content %}
<div class="card text-left">
    <div class="card-body">
        <div class="mb-3" style="display:flex; justify-content: space-between; align-items: center;">
            <h4 class="card-title mb-3">AGM list</h4>
            <a href="{% url 'company:agm_create' %}" class="btn btn-outline-primary">Add</a>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info" role="alert">
            <strong class="text-capitalize">Message!</strong> {{ message }}.
            <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Date</th>
                        <th scope="col">File</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in agm_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ data.title }}</td>
                        <td>{{ data.date }}</td>
                        <td><a href="{{ data.file.url }}" target="_blank">{{ data.file.url }}</a></td>
                        <td>
                            <a href="{% url 'company:agm_update' data.slug %}" class="btn btn-sm btn-outline-primary mr-2">Update</a>
                            <a href="{% url 'company:agm_delete' data.slug %}" class="btn btn-sm btn-outline-danger mr-2">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

company/templates/company/category_list.html
{% extends 'base.html' %}
{% block title %} Category | List {% endblock %}
{% block content %}
<div class="card text-left">
    <div class="card-body">
        <div style="display:flex; justify-content: space-between; align-items: center;">
            <h4 class="card-title mb-3">Category list</h4>
            <a href="{% url 'company:category_create' %}" class="btn btn-outline-primary">Add</a>
        </div>
        <p>Below are the list of categories</p>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info" role="alert">
            <strong class="text-capitalize">Message!</strong> {{ message }}.
            <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categories %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ category.name }}</td>
                        <td>
                            <a class="btn btn-sm btn-outline-primary mr-2"
                                href="{% url 'company:category_update' category.id %}">
                                Update
                            </a>
                            <a class="btn btn-sm btn-outline-danger mr-2"
                                href="{% url 'company:category_delete' category.id %}">
                                Delete
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

company/templates/company/company_delete.html
{% extends 'base.html' %}

{% block title %}
Company | Delete
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Delete confirmation</h5>
        <p class="card-text">
            Do you want to delete {{ company.name }}?
        </p>

        <a class="card-link btn btn-outline-success" href="{% url 'company:company_list' %}">Cancel</a>
        <form action="{% url 'company:company_delete' company.id %}" method="POST" style="display: inline;"
            class="ml-2">
            {% csrf_token %}
            <button class="card-link btn btn-outline-danger" type="submit">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

company/templates/company/company_update.html
{% extends 'base.html' %}

{% block title %} Company | Update {% endblock %}

{% block content %}
<div class="card mb-4">
    <div class="card-body">
        <div class="card-title mb-3">Update Company</div>
        <form action="{% url 'company:company_update' company.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">
                <strong class="text-capitalize">Info: </strong> {{ message }}.
                <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            {% endfor %}
            {% endif %}
            {% if form.errors %}
            {% for error in form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong class="text-capitalize">Error!</strong> {{ error }}.
                <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            {% endfor %}
            {% endif %}
            <div class="row">
                {% for field in form %}
                <div class="col-md-6 form-group mb-3">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-outline-success">Save</button>
        </form>
    </div>
</div>

<div class="card mb-4">
    <div class="card-body">
        <div class="card-title mb-3">Update Company url</div>
        <form action="{% url 'company:update_company_url' company.urls.id %}" method="POST">
            {% csrf_token %}
            <div class="row">
                {% for field in company_url_form %}
                <div class="col-md-6 form-group mb-3">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-outline-success">Save</button>
        </form>
    </div>
</div>

<div class="card mb-4">
    <div class="card-body" style="display: flex; align-items: center; justify-content: space-between;">
        <div class="card-title mb-3">Board of directors</div>
        <a href="{% url 'company:board_of_director_create' %}" class="btn btn-outline-primary">Add</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Designation</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for member in company.board_of_director.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td scope="row">{{ member.name }}</td>
                        <td scope="row">{{ member.designation }}</td>
                        <td>
                            <a href="{% url 'company:board_of_director_update' member.id %}"
                                class="btn btn-sm btn-outline-primary">Update</a>
                            <a href="{% url 'company:board_of_director_delete' member.id %}"
                                class="btn btn-sm btn-outline-danger">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

company/templates/company/floorsheet_list.html
{% extends 'base.html' %}

{% block title %}
Floorsheet | List
{% endblock %}

{% block content %}
<div class="card mb-4">
    <div class="card-body" style="display: flex; align-items: center; justify-content: space-between;">
        <div class="card-title mb-3">Floorsheets</div>
        <a href="{% url 'company:floorsheet_create' %}" class="btn btn-outline-primary">Add</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Company</th>
                        <th scope="col">Buyer</th>
                        <th scope="col">Seller</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Rate</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for floorsheet in floorsheets %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td scope="row">{{ floorsheet.company }}</td>
                        <td scope="row">{{ floorsheet.buyer }}</td>
                        <td scope="row">{{ floorsheet.seller }}</td>
                        <td scope="row">{{ floorsheet.quantity }}</td>
                        <td scope="row">{{ floorsheet.rate }}</td>
                        <td scope="row">{{ floorsheet.amount }}</td>
                        <td>
                            <a href="{% url 'company:floorsheet_update' floorsheet.id %}"
                                class="btn btn-sm btn-outline-primary">Update</a>
                            <a href="{% url 'company:floorsheet_delete' floorsheet.id %}"
                                class="btn btn-sm btn-outline-danger">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

company/templates/company/today_floorsheet.html
{% extends 'base.html' %}

{% block title %}
Floorsheet | Today
{% endblock %}

{% block content %}
<div class="card mb-4">
    <div class="card-body" style="display: flex; align-items: center; justify-content: space-between;">
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 16px;">
            <!-- <a href="{% url 'company:floorsheet_create' %}" class="btn btn-outline-primary">Add</a> -->
            <form action="{% url 'company:import_company_data' %}" method="POST" enctype="multipart/form-data" style="display: flex; align-items: center; justify-content: space-between; gap: 16px;">
                {% csrf_token %}
                <input type="file" name="file">
                <button type="submit" class="btn btn-outline-primary">Export as XLS</button>
            </form>
        </div>
    </div>
</div>
<div class="card mb-4">
    <div class="card-body" style="display: flex; align-items: center; justify-content: space-between;">
        <div class="card-title mb-3">Today's Market</div>
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 16px;">
            <!-- <a href="{% url 'company:floorsheet_create' %}" class="btn btn-outline-primary">Add</a> -->
            <form  method="POST" style="display: flex; align-items: center; justify-content: space-between; gap: 16px;">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-primary" name="pdf">Export as PDF</button>
                <button type="submit" class="btn btn-outline-primary" name="xls">Export as XLS</button>
            </form>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Logo</th>
                        <th scope="col">Company</th>
                        <th scope="col">LTP</th>
                        <th scope="col">Last updated at</th>
                    </tr>
                </thead>
                <tbody>
                    {% for company_data in sorted_company_data %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <th>
                            <img src="{{ company_data.company.logo.url }}" alt="{{ company_data.company.name }} logo"
                                width="50px">
                        </th>
                        <td scope="row">
                            {{ company_data.company.name }} <br>
                            <small>{{ company_data.company.symbol|upper }}</small>
                        </td>
                        <td scope="row">{{ company_data.last_traded_price }}</td>
                        <td scope="row">{{ company_data.updated_at }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}