account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.loginView, name='login_view'),
    path('create/', views.user_create_view, name='user_create'),
    path('user_list/', views.user_list, name='user_list'),
    path('update/<int:user_id>/', views.user_update, name='user_update'),
    path('delete/<int:user_id>/', views.user_delete, name='user_delete'),
    path('logout/', views.logout_view, name='logout_view'),
    path('group/list/', views.group_list, name='group_list'),
    path('group/create/', views.group_create, name='group_create'),
    path('group/update/<int:group_id>/', views.group_update, name='group_update'),
    path('group/delete/<int:group_id>/', views.group_delete, name='group_delete'),
    path('watchlist/add/<int:company_id>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('watchlist/remove/<int:company_id>/', views.remove_from_watchlist, name='remove_from_watchlist'),
    path('handle-agm-notification/<int:agm_id>/', views.handle_agm_notification_action, name='handle_agm_notification_action')
]

company/urls.py
from django.urls import path
from . import views

app_name = 'company'

urlpatterns = [
    path('', views.company_list, name='company_list'),
    path('create/', views.company_create, name='company_create'),
    path('update/<int:company_id>/', views.company_update, name='company_update'),
    path('delete/<int:company_id>/', views.company_delete, name='company_delete'),
    path('company_url_update/<int:company_url_id>/', views.update_company_url, name='update_company_url'),
    path('bod/create/', views.board_of_director_create, name='board_of_director_create'),
    path('bod/update/<int:bod_id>/', views.board_of_director_update, name='board_of_director_update'),
    path('bod/delete/<int:bod_id>/', views.board_of_director_delete, name='board_of_director_delete'),
    path('category/list', views.category_list, name='category_list'),
    path('category/create', views.category_create, name='category_create'),
    path('category/update/<int:category_id>/', views.category_update, name='category_update'),
    path('category/delete/<int:category_id>/', views.category_delete, name='category_delete'),
    path('floorsheet/list', views.floorsheet_list, name='floorsheet_list'),
    path('floorsheet/create', views.floorsheet_create, name='floorsheet_create'),
    path('floorsheet/update/<int:floorsheet_id>/', views.floorsheet_update, name='floorsheet_update'),
    path('floorsheet/delete/<int:floorsheet_id>/', views.floorsheet_delete, name='floorsheet_delete'),
    path('market/today/', views.today_market, name='today_market'),
    path('import/company/', views.import_company_data, name='import_company_data'),
    path('chart/data/<int:company_id>/', views.company_data_chart, name='company_data_chart'),
    path('data/create', views.company_data_create, name='company_data_create'),
    path('agm/list/', views.agm_list, name='agm_list'),
    path('agm/create/', views.agm_create, name='agm_create'),
    path('agm/update/<slug:agm_slug>/', views.agm_update, name='agm_update'),
    path('agm/delete/<slug:agm_slug>/', views.agm_delete, name='agm_delete'),
]

scrapper/urls.py
from django.urls import path
from . import views

app_name = 'scrapper'

urlpatterns = [
    path('detail/', views.company_detail, name='company_detail'),
    path('detail/admin/<int:company_id>/', views.company_detail_admin, name='company_detail_admin'),
    path('nepse/<int:company_id>/', views.scrap_from_nepse, name='scrap_from_nepse'),
    path('merolagani/<int:company_id>/', views.scrap_from_mero_lagani, name='scrap_from_mero_lagani'),
    path('sharesansar/<int:company_id>/', views.scrap_from_share_sansar, name='scrap_from_share_sansar'),
]

scrapping_2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import dashboard

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('company/', include('company.urls', namespace='company')),
    path('scrapper/', include('scrapper.urls', namespace='scrapper')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %} {% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,600,700,800,900" rel="stylesheet" />
    <link href="{% static 'css/themes/lite-purple.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/plugins/perfect-scrollbar.min.css' %}" rel="stylesheet" />
</head>

<body class="text-left">
    <div class="app-admin-wrap layout-sidebar-large">
        {% include 'navbar.html' %}
        {% include 'sidebar.html' %}

        <div class="main-content-wrap d-flex flex-column sidenav-open">
            <div class="main-content">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    <script src="{% static 'js/plugins/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/plugins/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'js/scripts/script.min.js' %}"></script>
    <script src="{% static 'js/scripts/sidebar.large.script.min.js' %}"></script>
    <script src="{% static 'js/plugins/echarts.min.js' %}"></script>
    <script src="{% static 'js/scripts/echart.options.min.js' %}"></script>
    <script src="{% static 'js/scripts/dashboard.v1.script.min.js' %}"></script>
    <script src="{% static 'js/scripts/customizer.script.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    
    {% block js %}
    {% endblock %}
</body>

</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<div class="card text-left mb-4">
    <div class="card-body">
        {% include 'message.html' %}
        {% if agm_notification_list %}
        {% for notification in agm_notification_list %}
        {% if notification.show_again %}
        <div class="alert alert-secondary" role="alert">
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <span>
                    {{ notification.company.name }} - {{ notification.agm.title }}. Date: {{ notification.agm.date }}. {{ notification.show_again }}
                </span>
                <form action="{% url 'account:handle_agm_notification_action' notification.agm.id  %}" method="POST" style="display: inline-flex; gap: 16px;" class="ml-4">
                    {% csrf_token %}
                    <button data-dismiss="alert" name="remind_me_later" style="background-color: transparent; border: none; text-decoration: underline;">Remind me later</button>
                    <button type="submit" name="do_not_show_again" style="background-color: transparent; border: none; text-decoration: underline;">Do not show again</button>
                </form>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
        <h4 class="card-title mb-3">Hello, {{ request.user.first_name }}</h4>
        <div id="search-form-container" class="mb-4">
            <form style="display: flex; align-items: flex-end; gap: 16px;" >
               <div style="display: inline-flex; flex-direction: column; align-items: flex-start;">
                    <label for="search">Search company</label>
                    <input type="text" id="search" name="search" placeholder="Enter company name or symbol" class="form-control" value="{{ search_keyword }}" required>
               </div>
               <button class="btn btn-outline-primary">Search</button>
            </form>
        </div>
        {% if search_results %}
        <p>Showing result for "{{ search_keyword }}"</p>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Logo</th>
                        <th scope="col">Company Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in search_results %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td scope="row">
                            <img src="{{ data.logo.url }}" alt="{{ data.name }} logo" height="40px">
                        </td>
                        <td scope="row">{{ data.name }}</td>
                        <td scope="row">{{ data.category.name }}</td>
                        <td scope="row"><a href="{% url 'account:add_to_watchlist' data.id %}" class="btn btn-sm btn-outline-primary">Add to watch list</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h5 class="card-title mb-3">Your watchlist</h5>
        {% if watch_list %}
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <th scope="col">Logo</th>
                    <th scope="col">Company Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">LTP</th>
                    <th scope="col">Source</th>
                    <th scope="col">Updated at</th>
                    <th scope="col">Action</th>
                </thead>
                <tbody>
                    {% for data in watch_list_data  %}
                    <tr>
                        <td>
                            <img src="{{ data.company.logo.url }}" alt="{{ data.company.name }} logo" height="40px" >
                        </td>
                        <td>{{ data.company.name }}</td>
                        <td>{{ data.company.category.name }}</td>
                        <td>{{ data.last_traded_price }}</td>
                        <td>{{ data.last_scrapped_from }}</td>
                        <td>{{ data.updated_at }}</td>
                        <td><a href="{% url 'account:remove_from_watchlist' data.company.id %}" class="btn btn-sm btn-outline-danger">Remove from watch list</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p>No items on wishlist</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/message.html
{% if messages %}
{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger" role="alert">
    {{ message }}
    <button class="close" type="button" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
{% else %}
<div class="alert alert-success" role="alert">
    {{ message }}
    <button class="close" type="button" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
{% endif %}
{% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
<div class="main-header">
    <div class="logo">
        <img src="/static/images/logo.png" alt="">
    </div>
    <div class="menu-toggle">
        <div></div>
        <div></div>
        <div></div>
    </div>
    <div class="d-flex align-items-center">
        <!-- Mega menu -->
        <div class="dropdown mega-menu d-none d-md-block">
            <a href="#" class="btn text-muted dropdown-toggle mr-3" id="dropdownMegaMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">Mega Menu</a>
            <div class="dropdown-menu text-left" aria-labelledby="dropdownMenuButton">
                <div class="row m-0">
                    <div class="col-md-4 p-4 bg-img">
                        <h2 class="title">Mega Menu <br> Sidebar</h2>
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores natus laboriosam fugit,
                            consequatur.
                        </p>
                        <p class="mb-4">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Exercitationem odio
                            amet eos dolore suscipit placeat.</p>
                        <button class="btn btn-lg btn-rounded btn-outline-warning">Learn More</button>
                    </div>
                    <div class="col-md-4 p-4">
                        <p class="text-primary text--cap border-bottom-primary d-inline-block">Features</p>
                        <div class="menu-icon-grid w-auto p-0">
                            <a href="#"><i class="i-Shop-4"></i> Home</a>
                            <a href="#"><i class="i-Library"></i> UI Kits</a>
                            <a href="#"><i class="i-Drop"></i> Apps</a>
                            <a href="#"><i class="i-File-Clipboard-File--Text"></i> Forms</a>
                            <a href="#"><i class="i-Checked-User"></i> Sessions</a>
                            <a href="#"><i class="i-Ambulance"></i> Support</a>
                        </div>
                    </div>
                    <div class="col-md-4 p-4">
                        <p class="text-primary text--cap border-bottom-primary d-inline-block">Components</p>
                        <ul class="links">
                            <li><a href="#">Accordion</a></li>
                            <li><a href="#">Alerts</a></li>
                            <li><a href="#">Buttons</a></li>
                            <li><a href="#">Badges</a></li>
                            <li><a href="#">Carousels</a></li>
                            <li><a href="#">Lists</a></li>
                            <li><a href="#">Popover</a></li>
                            <li><a href="#">Tables</a></li>
                            <li><a href="#">Datatables</a></li>
                            <li><a href="#">Modals</a></li>
                            <li><a href="#">Sliders</a></li>
                            <li><a href="#">Tabs</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- / Mega menu -->
        <div class="search-bar">
            <input type="text" placeholder="Search" fdprocessedid="kpx9xl">
            <i class="search-icon text-muted i-Magnifi-Glass1"></i>
        </div>
    </div>
    <div style="margin: auto"></div>
    <div class="header-part-right">
        <!-- Full screen toggle -->
        <i class="i-Full-Screen header-icon d-none d-sm-inline-block" data-fullscreen=""></i>
        <!-- Grid menu Dropdown -->
        <div class="dropdown">
            <i class="i-Safe-Box text-muted header-icon" role="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <div class="menu-icon-grid">
                    <a href="#"><i class="i-Shop-4"></i> Home</a>
                    <a href="#"><i class="i-Library"></i> UI Kits</a>
                    <a href="#"><i class="i-Drop"></i> Apps</a>
                    <a href="#"><i class="i-File-Clipboard-File--Text"></i> Forms</a>
                    <a href="#"><i class="i-Checked-User"></i> Sessions</a>
                    <a href="#"><i class="i-Ambulance"></i> Support</a>
                </div>
            </div>
        </div>
        <!-- Notificaiton -->
        <div class="dropdown" id="notification-btn">
            <div class="badge-top-container" role="button" id="dropdownNotification" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="badge badge-primary" id="notification-count">{{ agm_notification_list|length }}</span>
                <i class="i-Bell text-muted header-icon"></i>
            </div>

            <!-- Notification dropdown -->
            <div class="dropdown-menu dropdown-menu-right notification-dropdown rtl-ps-none ps"
                aria-labelledby="dropdownNotification" data-perfect-scrollbar="" data-suppress-scroll-x="true">
                {% if agm_notification_list %}
                {% for notification in agm_notification_list %}
                <div class="dropdown-item d-flex">
                    <div class="notification-details flex-grow-1">
                        <p class="m-0 d-flex align-items-center">
                            <span>{{ notification.agm.title }} | {{ notification.show_again }}</span>
                            <span class="flex-grow-1"></span>
                        </p>
                        <p class="text-small text-muted m-0">{{ notification.agm.description }}</p>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
                <div class="ps__rail-x" style="left: 0px; bottom: 0px;">
                    <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div>
                </div>
                <div class="ps__rail-y" style="top: 0px; right: 0px;">
                    <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div>
                </div>
            </div>
        </div>
        <!-- Notificaiton End -->
        <!-- User avatar dropdown -->
        <div class="dropdown">
            <div class="user col align-self-end">
                <img src="{% static '/images/faces/1.jpg' %}" id="userDropdown" alt="" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    {% if user.is_authenticated %}
                    <div class="dropdown-header">
                        <i class="i-Lock-User mr-1"></i> {{ request.user.full_name }}
                    </div>
                    <a class="dropdown-item" href="{% url 'account:logout_view' %}">Sign out</a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'account:login_view' %}">Sign in</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% block js %}
<script>
    const notificationBtn = document.getElementById("notification-btn");
    const notificationBadge = document.getElementById("notification-count");
    notificationBtn.addEventListener('click', () => {
        console.log("clicked");
        notificationBadge.remove()
    })
</script>
{% endblock %}

templates/sidebar.html
{% load group_tags %}
<div class="side-content-wrap">
    <div class="sidebar-left rtl-ps-none ps ps--active-y open" data-perfect-scrollbar="" data-suppress-scroll-x="true">
        <ul class="navigation-left">
            <li class="nav-item">
                <a class="nav-item-hold" href="{% url 'dashboard' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" style="height: 26px;">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M7.5 14.25v2.25m3-4.5v4.5m3-6.75v6.75m3-9v9M6 20.25h12A2.25 2.25 0 0 0 20.25 18V6A2.25 2.25 0 0 0 18 3.75H6A2.25 2.25 0 0 0 3.75 6v12A2.25 2.25 0 0 0 6 20.25Z" />
                    </svg>
                    <span class="nav-text">Dashboard</span></a>
                <div class="triangle"></div>
            </li>
            {% if request.user|user_in_groups:"super admin, super editor" %}
            <li class="nav-item" data-item="users">
                <a class="nav-item-hold" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" style="height: 26px">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M18 18.72a9.094 9.094 0 0 0 3.741-.479 3 3 0 0 0-4.682-2.72m.94 3.198.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0 1 12 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 0 1 6 18.719m12 0a5.971 5.971 0 0 0-.941-3.197m0 0A5.995 5.995 0 0 0 12 12.75a5.995 5.995 0 0 0-5.058 2.772m0 0a3 3 0 0 0-4.681 2.72 8.986 8.986 0 0 0 3.74.477m.94-3.197a5.971 5.971 0 0 0-.94 3.197M15 6.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm6 3a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Zm-13.5 0a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Z" />
                    </svg>

                    <span class="nav-text">Users</span></a>
                <div class="triangle"></div>
            </li>
            <li class="nav-item" data-item="company">
                <a class="nav-item-hold" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" style="height: 26px;">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M3.75 21h16.5M4.5 3h15M5.25 3v18m13.5-18v18M9 6.75h1.5m-1.5 3h1.5m-1.5 3h1.5m3-6H15m-1.5 3H15m-1.5 3H15M9 21v-3.375c0-.621.504-1.125 1.125-1.125h3.75c.621 0 1.125.504 1.125 1.125V21" />
                    </svg>

                    <span class="nav-text">Company</span></a>
                <div class="triangle"></div>
            </li>
            <li class="nav-item" data-item="category">
                <a class="nav-item-hold" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" style="height: 26px;">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M3.75 6A2.25 2.25 0 0 1 6 3.75h2.25A2.25 2.25 0 0 1 10.5 6v2.25a2.25 2.25 0 0 1-2.25 2.25H6a2.25 2.25 0 0 1-2.25-2.25V6ZM3.75 15.75A2.25 2.25 0 0 1 6 13.5h2.25a2.25 2.25 0 0 1 2.25 2.25V18a2.25 2.25 0 0 1-2.25 2.25H6A2.25 2.25 0 0 1 3.75 18v-2.25ZM13.5 6a2.25 2.25 0 0 1 2.25-2.25H18A2.25 2.25 0 0 1 20.25 6v2.25A2.25 2.25 0 0 1 18 10.5h-2.25a2.25 2.25 0 0 1-2.25-2.25V6ZM13.5 15.75a2.25 2.25 0 0 1 2.25-2.25H18a2.25 2.25 0 0 1 2.25 2.25V18A2.25 2.25 0 0 1 18 20.25h-2.25A2.25 2.25 0 0 1 13.5 18v-2.25Z" />
                    </svg>
                    <span class="nav-text">Category</span></a>
                <div class="triangle"></div>
            </li>
            <li class="nav-item">
                <a class="nav-item-hold" href="{% url 'company:today_market' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="height: 26px;">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 8.25H9m6 3H9m3 6-3-3h1.5a3 3 0 1 0 0-6M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                    </svg>
                    <span class="nav-text">Today's Market</span></a>
                <div class="triangle"></div>
            </li>
            <li class="nav-item" data-item="agm">
                <a class="nav-item-hold">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="height: 26px;">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5" />
                    </svg>                      
                    <span class="nav-text">AGM</span></a>
                <div class="triangle"></div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-item-hold" href="{% url 'scrapper:company_detail' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" style="height: 26px;">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M3.75 21h16.5M4.5 3h15M5.25 3v18m13.5-18v18M9 6.75h1.5m-1.5 3h1.5m-1.5 3h1.5m3-6H15m-1.5 3H15m-1.5 3H15M9 21v-3.375c0-.621.504-1.125 1.125-1.125h3.75c.621 0 1.125.504 1.125 1.125V21" />
                    </svg>
                    <span class="nav-text">Company</span></a>
                <div class="triangle"></div>
            </li>
            {% endif %}
        </ul>
        <div class="ps__rail-x" style="left: 0px; bottom: 0px">
            <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px"></div>
        </div>
        <div class="ps__rail-y" style="top: 0px; height: 615px; right: 0px">
            <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 308px"></div>
        </div>
    </div>
    <div class="sidebar-left-secondary rtl-ps-none ps" data-perfect-scrollbar="" data-suppress-scroll-x="true">
        {% if request.user|user_in_groups:"super admin, super editor" %}
        <ul class="childNav" data-parent="company" style="display: block">
            <li class="nav-item">
                <a href="{% url 'company:company_list' %}">
                    <span class="item-name">Company list</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'company:company_create' %}">
                    <span class="item-name">Add Company</span>
                </a>
            </li>
        </ul>
        <ul class="childNav" data-parent="agm" style="display: block">
            <li class="nav-item">
                <a href="{% url 'company:agm_list' %}">
                    <span class="item-name">AGM list</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'company:agm_create' %}">
                    <span class="item-name">Add AGM</span>
                </a>
            </li>
        </ul>
        <ul class="childNav" data-parent="users" style="display: block">
            <li class="nav-item">
                <a href="{% url 'account:user_list' %}">
                    <span class="item-name">User list</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'account:group_list' %}">
                    <span class="item-name">Group list</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'account:user_create' %}">
                    <span class="item-name">Add User</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'account:group_create' %}">
                    <span class="item-name">Add Group</span>
                </a>
            </li>
        </ul>
        <ul class="childNav" data-parent="category" style="display: block">
            <li class="nav-item">
                <a href="{% url 'company:category_list' %}">
                    <span class="item-name">Category list</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'company:category_create' %}">
                    <span class="item-name">Add category</span>
                </a>
            </li>
        </ul>
        {% endif %}
        <div class="ps__rail-x" style="left: 0px; bottom: 0px">
            <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px"></div>
        </div>
        <div class="ps__rail-y" style="top: 0px; right: 0px">
            <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px"></div>
        </div>
    </div>
    <div class="sidebar-overlay"></div>
</div>